AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ordersapi

Globals:
  Function:
    Runtime: python3.8
    Timeout: 30
    Environment:
      Variables:
        ORDERS_TABLE: !Ref OrdersTable

Resources:
  OrdersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: Number

  CreateOrderFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ordersapi/
      Handler: create.lambda_handler
      Events:
        CreateOrders:
          Type: Api
          Properties:
            Path: /orders
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdersTable

  ReadOrderFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ordersapi/
      Handler: read.lambda_handler
      Events:
        ReadOrders:
          Type: Api
          Properties:
            Path: /orders/{id}
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref OrdersTable

  DataTypesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ordersapi/
      Handler: datatypes.dict_types
      Environment:
        Variables:
          restapiurl: http://dummyurl
          dbname: mydb      

Outputs:
  CreateOrdersAPI:
    Description: "API Gateway endpoint url for creating orders"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/orders"
  CreateOrderFunction:
    Description: "Create Order function ARN"
    Value: !GetAtt CreateOrderFunction.Arn
  CreateOrderFunctionIamRole:
    Description: "Create Order function IAM Role ARN"
    Value: !GetAtt CreateOrderFunctionRole.Arn
  CreateDataTypesFunction:
    Description: "Create DataType function ARN"
    Value: !GetAtt DataTypesFunction.Arn
